### ISSUE TITLE
Can you release the dat file?

### ISSUE THREAD

**Issue by mohanson** [miaoerduo/dlib-face-landmark-compression#1]
I tried to build it myself but I failed. I'm not sure if it's my problem or your project or something else, so I'd appreciate it if you could release the SMALLER dat file on the repo.

The problem is there is no INCLUDE and LIB path in my dlib root path... I am sure I installed dlib correctly because I used it months.

**Comment by miaoerduo** [comment]
Sorry for replying you so late，I have released the model file。
link: https://pan.baidu.com/s/1pMwHtpx  password: mqt5

I use a command like this to compile the project:
```
g++ main.cpp -o main.bin -I ./ -I /home/software/dlib/19.8/include/ -L /home/software/dlib/19.8/lib -ldlib -std=c++11
```
maybe you should replace `DLIB_PATH` by your local path.
