### ISSUE TITLE
unsigned long is not compatible between 32bit and 64bit system

### ISSUE THREAD

**Issue by Pinnh** [miaoerduo/dlib-face-landmark-compression#2]
unsigned long is not compatible between 32bit and 64bit system,when use 64bit system to convert model and then load to 32bit system will get wrong result

**Comment by Pinnh** [comment]
suggest to use unsigned int to replace unsigned long

**Comment by miaoerduo** [comment]
Thanks for your feedback! The problem does exist.
And I fixed the bug by replacing `long` to `long long` as this type `long long` is always 8 bytes in different systems.
Thanks for people like you for making github a best place to share and learn together. @Pinnh 🙂

**Comment by Pinnh** [comment]
no matter~
