### ISSUE TITLE
ERROR: Error deserializing object of type int

### ISSUE THREAD

**Issue by Roger8** [miaoerduo/dlib-face-landmark-compression#4]
exception thrown!
An error occurred while trying to read the first object from the file /home/roger/shape_predictor_68_face_landmarks_small.dat.
ERROR: Error deserializing object of type int 
@miaoerduo , 请问直接用你压缩后的模型的话，也需要修改shapepredictor.h 里的成员属性吗？

**Comment by miaoerduo** [comment]
您好，你这个错误是不是使用了dlib::deserialize 这个函数去加载压缩之后的模型然后抛出的？
压缩之后的模型的数据格式和原模型完全不同，应该使用这里的med::load_shape_predictor_model 来加载。您可以参考一下main.cpp的示例。有问题请随时告知。

**Comment by miaoerduo** [comment]
调用模型的话，也是需要把成员改成public。另一个方案就是添加友元，但这个要改的地方就更多了。@Roger8

**Comment by Roger8** [comment]
明白。 @miaoerduo 遇到另一个问题：我修改   face_landmark_detection_ex.cpp, 用你的med::load_shape_predictor_model 来加载model 
编译的时候报错：
/bin/ld: /tmp/ccBBuvvQ.o: undefined reference to symbol 'cblas_sscal'
/usr/local/lib/libopenblas.so.0: error adding symbols: DSO missing from command line @miaoerduo

**Comment by miaoerduo** [comment]
这个有点奇怪，因为代码里面似乎没有用到openblas。您可以跑通项目demo的代码吗？
另外，DSO missing的问题，可以查到相关的解决方案，应该是和链接库相关。这可能是和您的项目的其他部分有关。
这里还是建议您先运行一下demo。@Roger8

**Comment by Roger8** [comment]
@miaoerduo 路径设置问题，现在可以运行了, 多谢

**Comment by cvtower** [comment]
Good Job!

However, i include totally same modified source files of dlib and this repo, and:
i port this project to android platform(ndk 64) and it works fine, but all loaded paras are wrong on windows platform(vs2015 64).
wired.

**Comment by miaoerduo** [comment]
@cvtower 
I am sorry, I didn't test this project on all platforms.
Maybe you could create the compressed model and load the model in the same system. My given compressed model is created on MacOS@64。
