### ISSUE TITLE
如果想在python里用这个模型，需要什么操作么

### ISSUE THREAD

**Issue by hufengshuo07** [miaoerduo/dlib-face-landmark-compression#6]
另外精度相当于原模型，但是速度会提高许多吗?

**Comment by miaoerduo** [comment]
@hufengshuo07 

应该需要写一个C的库，调用这里的Cpp接口，然后导出来。
Python可以用ctype等工具来调用so的库。

模型运行速度和原模型是一致的，只是模型文件压缩了，精度略低一点。

**Comment by hufengshuo07** [comment]
👌🏻 谢谢谢谢
